DELETE FROM Alias WHERE UTASK in (SELECT [NAME] FROM Clases WHERE IDTO in (SELECT IDTO FROM S_Report))
DELETE FROM S_Report
DELETE FROM S_SubReport
DELETE FROM Clases WHERE IDTO<0
DELETE FROM properties WHERE PROP<0
DELETE FROM T_Herencias WHERE ID_TO<0
DELETE FROM instances WHERE IDTO<0
DELETE FROM Access WHERE IDTO<0
DELETE FROM Groups WHERE ID<0
